Class {
	#name : #SistemaDeArchivos,
	#superclass : #Object,
	#instVars : [
		'root'
	],
	#category : #'O2-FileSystem'
}

{ #category : #'as yet unclassified' }
SistemaDeArchivos >> archivoMasGrande [ 
^root archivoMasGrande 
]

{ #category : #'as yet unclassified' }
SistemaDeArchivos >> archivoMasNuevo [ 
^root  archivoMasNuevo 
]

{ #category : #'as yet unclassified' }
SistemaDeArchivos >> listadoDeContenido [ 
^root listadoDeContenido 
]
